### ISSUE TITLE
SNSアプリの初回起動時クラッシュ調査

### ISSUE THREAD

**Issue by aoki2002** [aoki2002/sns_app#3]
## 実現したいこと
- 画面遷移設定した上での初回起動時スタート画面表示

## 現状 

- StartView
```
class StartView: Fragment() {

    private lateinit var binding: FragmentStartBinding

    private val startViewModel = StartViewModel()

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        super.onCreateView(inflater, container, savedInstanceState)

        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_start, container, false)

        binding.viewModel = startViewModel

        binding.lifecycleOwner = this

        return binding.root

    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val navController = view.findNavController()

        startViewModel.check()

        Handler()
            .postDelayed (
                {
                    if ( startViewModel.checkIsEnable == true) {

                        navController.navigate(R.id.action_StartFragment_to_MainFragment)
                    } else {

                        navController.navigate(R.id.action_StartFragment_to_SignInFragment)
                    }
                }
                , 3000
            )
    }
}
```
- Javaエラー
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sns_app/com.example.sns_app.Activity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3010)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3145)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1900)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6846)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)                                                                          	                                                                
```
- XMLエラー
```
Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.example.sns_app.view.StartView: calling Fragment constructor caused an exception
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:690)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:525)
	at androidx.navigation.fragment.FragmentNavigator.createFragmentTransaction(FragmentNavigator.kt:394)
	at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.kt:329)
	at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.kt:308)
	at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.kt:92)
	at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.kt:58)
	at androidx.navigation.NavController.navigateInternal(NavController.kt:265)
	at androidx.navigation.NavController.navigate(NavController.kt:1832)
	at androidx.navigation.NavController.onGraphCreated(NavController.kt:1274)
	at androidx.navigation.NavController.setGraph(NavController.kt:1186)
	at androidx.navigation.NavController.setGraph(NavController.kt:1139)
	at androidx.navigation.fragment.NavHostFragment$navHostController$2.invoke(NavHostFragment.kt:104)
	at androidx.navigation.fragment.NavHostFragment$navHostController$2.invoke(NavHostFragment.kt:78)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.navigation.fragment.NavHostFragment.getNavHostController$navigation_fragment_release(NavHostFragment.kt:78)
	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:150)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
2023-07-12 11:34:31.464  6724-6724  AndroidRuntime          com.example.sns_app                  E  	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:247)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:226)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at com.example.sns_app.Activity.onCreate(Activity.kt:9)
	at android.app.Activity.performCreate(Activity.java:7188)
	at android.app.Activity.performCreate(Activity.java:7179)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2990)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3145)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1900)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6846)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
```
- Firebaseエラー                                       
``` 
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.sns_app. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
	at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@22.0.0:1)
	at com.google.firebase.auth.ktx.AuthKt.getAuth(com.google.firebase:firebase-auth-ktx@@22.0.0:8)
	at com.example.sns_app.model.AuthenticationRepository.<init>(AuthenticationRepository.kt:8)
	at com.example.sns_app.viewmodel.StartViewModel.<init>(StartViewModel.kt:9)
```

**Comment by aoki2002** [comment]
## 検証1
- StartViewのViewModelのインスタンス化の記述を以下に変更

```
private val startViewModel: StartViewModel by viewModels()
```

## 検証結果
- ViewModelのインスタント化の記述を変更することで、XMLエラー解決

## 資料
- https://zenn.dev/nemototea/articles/d7fe9b095e3487
- https://zenn.dev/itakahiro/articles/93e32fb720ee95
- https://zenn.dev/itakahiro/articles/93e32fb720ee95

**Comment by aoki2002** [comment]
## 検証2
- AuthenticationRepositoryの各関数にFirebaseAuthインスタンス初期化する以下のコードを追加
```
auth = Firebase.auth
```

## 検証結果
- Javaエラーが一種類となった
```
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.sns_app. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
	at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@22.0.0:1)
	at com.google.firebase.auth.ktx.AuthKt.getAuth(com.google.firebase:firebase-auth-ktx@@22.0.0:8)
	at com.example.sns_app.model.AuthenticationRepository.checkAccount(AuthenticationRepository.kt:16)
	at com.example.sns_app.viewmodel.StartViewModel.check(StartViewModel.kt:15)
	at com.example.sns_app.view.StartView.onViewCreated(StartView.kt:40)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
	at android.app.Activity.performStart(Activity.java:7209)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3034)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1900)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6846)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
```

## 資料
- https://firebase.google.com/docs/auth/android/start?hl=ja

**Comment by aoki2002** [comment]
## 検証3
・FirebaseプロジェクトとKotlinプロジェクトとの紐付け

## 検証結果
・初期起動時クラッシュがなくなり、スタート画面が表示された
